# Generated by Django 4.2.2 on 2023-10-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='name',
            new_name='username',
        ),
    ]
