# Generated by Django 4.2.2 on 2023-07-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0002_alter_fillingstation_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillingstation',
            name='station_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
