# Generated by Django 4.2.2 on 2023-09-17 09:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0003_alter_fillingstation_station_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillingstation',
            name='station_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
