# Generated by Django 4.2.2 on 2023-09-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0004_alter_fillingstation_station_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillingstation',
            name='car_mechanic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='car_wash',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='mini_mart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='operation_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='pos',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
