# Generated by Django 4.2.2 on 2023-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0005_fillingstation_car_mechanic_fillingstation_car_wash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillingstation',
            name='car_mechanic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fillingstation',
            name='car_wash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fillingstation',
            name='mini_mart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fillingstation',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
