# Generated by Django 4.2.2 on 2023-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0006_alter_fillingstation_car_mechanic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillingstation',
            name='no_of_user_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fillingstation',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
