# Generated by Django 4.2.2 on 2023-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0007_fillingstation_no_of_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillingstation',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fillingstation',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
