# Generated by Django 4.2.2 on 2023-09-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0008_alter_fillingstation_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningHour',
        ),
    ]
