# Generated by Django 4.2.2 on 2023-09-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('filling_station', '0009_delete_openinghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ManyToManyField(to='filling_station.fillingstation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.generaluser')),
            ],
        ),
    ]
