# Generated by Django 4.2.2 on 2023-09-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0011_alter_favouritestation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritestation',
            old_name='user_id',
            new_name='user',
        ),
    ]
